### ISSUE TITLE
关于vocab size

### ISSUE THREAD

**Issue by yangliuIOC** [wdndev/tiny-llm-zh#11]
你好，使用glm3 len(tokenizer)  =64796, 为什么咱们这边model的vocab设置成 64798呢

**Comment by wdndev** [comment]
可以看一下这个，https://github.com/THUDM/ChatGLM3/issues/634

**Comment by yangliuIOC** [comment]
您好，看了上述的问题还是没太理解，因为 上述讨论中说 64796之后都没有具体使用，我理解设置成64796是不是是最合适的？

**Comment by wdndev** [comment]
嗯嗯，设置成64796也可以，可以试试
