### ISSUE TITLE
身份 认知

### ISSUE THREAD

**Issue by yangliuIOC** [wdndev/tiny-llm-zh#13]
博主，请问：怎么能够让模型知道你是xxx创造的，并且在任何类似问题中，都能回复出来我是xxx创造的

**Comment by wdndev** [comment]
SFT的时候加入认知数据集，基本就是那些常见的问题，比如：{“q”：“你是谁？”，“a”：“我是。。。”}之类的认知数据集，我记得我好像加了有个40  50条，自己写的一些常见的回复。
