### ISSUE TITLE
预训练的过程中报错:AttributeError: 'TinyllmConfig' object has no attribute 'sliding_window'

### ISSUE THREAD

**Issue by jzzzf** [wdndev/tiny-llm-zh#4]
请问可以怎么调整嘛

**Comment by wdndev** [comment]
我训练的时候没有走到另一个分支，没测试到

先检查一下 modeling_tinyllm.py 文件中 496 行是不是True，
![image](https://github.com/wdndev/tiny-llm-zh/assets/83126264/b52b104a-9505-456c-85ca-67fabf3f21ef)
然后删除 616行的那个就行：
![image](https://github.com/wdndev/tiny-llm-zh/assets/83126264/3fdb628a-0d25-44d7-b652-df31b6fa676a)

**Comment by jzzzf** [comment]
感谢,确实注释掉616行就可以了
